name: Run Selenium Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2:00 AM UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome
        run: |
          wget -q -O google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome.deb || sudo apt-get -f install -y
          which google-chrome || which google-chrome-stable
          google-chrome --version || google-chrome-stable --version

      - name: Install Chromedriver
        run: |
          # Try both possible Chrome executable names and extract version
          CHROME_VERSION=$(
            (google-chrome --version 2>/dev/null || google-chrome-stable --version) \
            | grep -oP '\d+\.\d+\.\d+'
          )
          echo "Detected Chrome version: $CHROME_VERSION"
          wget -q "https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          mv chromedriver-linux64/chromedriver .
          chmod +x chromedriver

      - name: Run scraper
        env:
          CHROMEDRIVER_PATH: ${{ github.workspace }}/chromedriver
        run: |
          python scraper
